<?php

function designssquare_com_site_loam_menu_footer_install(){
    $t = get_t();

    // clear menus and create new ones if doesn't exist
    foreach(_loam_footer_menus_altered() as $menu){
        //remove menu links for clean install
        menu_delete_links($menu);
        drupal_set_message($t('Links deleted from menu - ' . $menu['menu_name']));

        if(!menu_load($menu['menu_name'])){
            //doesn't exist...lets create one
            drupal_set_message($t('Missing menu '.$menu['menu_name'].'...creating'));
            menu_save($menu);
        }
    }

    //map containing the structure of the menu
    $alias_map = array();

    //shuffle so that parents are always above the children menu items
    //this is important so when building the $alias_map child is not being inserted without parent already present
    $all_items = _loam_footer_menu_installed_items();
    $parents_p1 = array();
    $parents_p2 = array();
    $parents_p3 = array();
    $parents_p4 = array();
    $parents_p5 = array();

    foreach($all_items as $key => $item){
        if($key == $item['p1']){
            $parents_p1[$key] = $item;
        }
        if($key == $item['p2']){
            $parents_p2[$key] = $item;
        }
        if($key == $item['p3']){
            $parents_p3[$key] = $item;
        }
        if($key == $item['p4']){
            $parents_p4[$key] = $item;
        }
        if($key == $item['p5']){
            $parents_p5[$key] = $item;
        }
    }

    $sorted_menu_list = array_merge($parents_p1,$parents_p2,$parents_p3,$parents_p4,$parents_p5);

    //add links
    foreach ($sorted_menu_list as $key => $item) {
        $alias_link_path = $item['link_path'];
        //look up node based on the alias path of existing drupal instance
        $item['link_path'] = drupal_get_normal_path($alias_link_path);

        //drupal_set_message('plid: '.$item['plid']. ' alias_map:' . $alias_map[$item['plid']] );
        $item['plid'] = ($item['plid'] !== 0 && !empty($alias_map[$item['plid']])) ? $alias_map[$item['plid']] : $item['plid'] ;
        $item['p1'] = ($item['p1'] !== 0 && !empty($alias_map[$item['p1']])) ? $alias_map[$item['p1']] : $item['p1'] ;
        $item['p2'] = ($item['p2'] !== 0 && !empty($alias_map[$item['p2']]) ) ? $alias_map[$item['p2']] : $item['p2'] ;
        $item['p3'] = ($item['p3'] !== 0 && !empty($alias_map[$item['p3']])) ? $alias_map[$item['p3']] : $item['p3'] ;

        $installed = menu_link_save($item);
        if($installed !== FALSE) {
            drupal_set_message($t('Menu Item : '. $key . ' installed'));
            //drupal_set_message('INSERT: link_path: '.$alias_link_path. ' mlip:' . $installed );
            $alias_map[$alias_link_path] = $installed;
        }else{
            drupal_set_message($t('Menu Item : '. $key . ' was not installed'));
        }
    }
    menu_link_save($item);
    menu_cache_clear_all();
    drupal_set_message($t('Footer Menu Installed'));
}

function _loam_footer_menus_altered(){
    return array (
        array('menu_name' => 'menu-footer-menu','title' => 'Footer Menu','description' => 'menu at the footer'),
    );
}


function _loam_footer_menu_installed_items() {
    return array (
        'sākums-latviesu-organizāciju-apvieniba-minesotā' => array(
            'menu_name' => 'menu-footer-menu',
            'plid' => '0',
            'link_path' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
            'link_title' => 'Sākums',
            'options' => array(
                'attributes' => array(
                    'title' => '',
                ),
            ),
            'module' => 'menu',
            'hidden' => '0',
            'external' => '0',
            'has_children' => '0',
            'expanded' => '0',
            'weight' => '0',
            'depth' => '1',
            'customized' => '1',
            'p1' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
            'p2' => '0',
            'p3' => '0',
            'p4' => '0',
            'p5' => '0',
            'p6' => '0',
            'p7' => '0',
            'p8' => '0',
            'p9' => '0',
            'updated' => '0',
        ),
        'latviesu-organizāciju-apvieniba-minesotā' => array(
            'menu_name' => 'menu-footer-menu',
            'plid' => '0',
            'link_path' => 'latviesu-organizāciju-apvieniba-minesotā',
            'link_title' => 'LOAM',
            'options' => array(
                'attributes' => array(
                    'title' => '',
                ),
            ),
            'module' => 'menu',
            'hidden' => '0',
            'external' => '0',
            'has_children' => '0',
            'expanded' => '0',
            'weight' => '1',
            'depth' => '1',
            'customized' => '1',
            'p1' => 'latviesu-organizāciju-apvieniba-minesotā',
            'p2' => '0',
            'p3' => '0',
            'p4' => '0',
            'p5' => '0',
            'p6' => '0',
            'p7' => '0',
            'p8' => '0',
            'p9' => '0',
            'updated' => '0',
        ),
        'ds-blog' => array(
            'menu_name' => 'menu-footer-menu',
            'plid' => '0',
            'link_path' => 'ds-blog',
            'link_title' => 'Avīze',
            'options' => array(
                'attributes' => array(
                    'title' => '',
                ),
            ),
            'module' => 'menu',
            'hidden' => '0',
            'external' => '0',
            'has_children' => '0',
            'expanded' => '0',
            'weight' => '3',
            'depth' => '1',
            'customized' => '1',
            'p1' => 'ds-blog',
            'p2' => '0',
            'p3' => '0',
            'p4' => '0',
            'p5' => '0',
            'p6' => '0',
            'p7' => '0',
            'p8' => '0',
            'p9' => '0',
            'updated' => '0',
        ),
        'content/kontakts' => array(
            'menu_name' => 'menu-footer-menu',
            'plid' => '0',
            'link_path' => 'content/kontakts',
            'link_title' => 'Kontakts',
            'options' => array(
                'attributes' => array(
                    'title' => '',
                ),
            ),
            'module' => 'menu',
            'hidden' => '0',
            'external' => '0',
            'has_children' => '0',
            'expanded' => '0',
            'weight' => '4',
            'depth' => '1',
            'customized' => '1',
            'p1' => 'content/kontakts',
            'p2' => '0',
            'p3' => '0',
            'p4' => '0',
            'p5' => '0',
            'p6' => '0',
            'p7' => '0',
            'p8' => '0',
            'p9' => '0',
            'updated' => '0',
        )
    );
}




