<?php
/**
 * @file
 * esignssquare_com_site_loam_data.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function esignssquare_com_site_loam_data_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '<em class="icon-resize-horizontal"></em>Max-width 1200px',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '02ef3937-6bc1-4e5f-b654-ee17695f988e',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"></em>jQuery plugins',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '067af360-f093-426f-8ca1-e75cc2d75a6d',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"> </em> MSP Draudze',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '10caebcb-ed8c-4b3f-9dcb-875bd61220b2',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-th"></em>12-column grid',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '11c89891-6ec7-48a6-9680-315d87774539',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"> </em> MKGPF',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1ca10335-3045-4d37-9f14-7953469c16be',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"></em> Latviešu Koncertapvienība MN',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '21b4ce7e-6d45-44fa-b8ff-914c6e3c5500',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"></em> KKM',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2395718f-175f-4676-8837-9e3d17a9a4b4',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"> </em> Daugavas Vanagi',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '23cd8c51-5f47-4dc9-8c6f-d3f3050e1579',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"> </em> Akadēmiskā kopa',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '27d927a9-6ea8-4df5-bc8f-4f60e586a4a1',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"> </em> TARTS',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5038f9aa-87db-426e-86f2-319c64ea1f80',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-list-alt"></em>Styleguide docs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6178e85c-7716-470a-8a84-6701569ff80b',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-resize-small"></em>Responsive design',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '660b13f6-046f-4a13-a889-65aa19fefd01',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"> </em> MSPD Koris',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '75efd7d9-b71e-4ba1-bd65-ea3abcf92a4f',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"> </em> SP Latviešu katoļu draudze',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7c69ea01-9c90-4b88-84cd-f11760e3ff66',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"> </em> LK Sabiedrība',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '85a1fb3f-d3af-49c6-b86c-f17cd22b4430',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"> </em> Perkonītis',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9ea8fdba-6165-4846-b47b-fe6a0e61010c',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"> </em> Latviešu Skola',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ba4da224-065c-4098-9ce3-664ac11eed7d',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-user"></em>Built for and by nerds',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd81daa80-66c6-4218-91d8-68365e3474a1',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"> </em> Teiksma',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dfd9df67-f88a-46e3-94bb-47cf29e29a78',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-book"></em>Growing library',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e30910ae-5afe-4f81-8f89-9b441451d456',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-eye-open"></em>Cross-everything',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e6440aab-17a5-407b-b97e-f37080cee43c',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class=" icon-cog"> </em> SELGA',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'fe40396c-8b2b-4c3d-a510-b139cda8970c',
    'vocabulary_machine_name' => 'features',
  );
  return $terms;
}
