<?php
/**
 * @file
 * esignssquare_com_site_loam_data.features.inc
 */

/**
 * Implements hook_content_assets_default_settings().
 */
function esignssquare_com_site_loam_data_content_assets_default_settings() {
$content_assets = array();

$content_assets = array(
  'public://designssquare_com/widget/gallery/bio-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/bio-lg.jpg',
    'filename' => 'bio-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdfat-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdfat-lg.jpg',
    'filename' => 'birdfat-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdfat-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdfat-lg_0.jpg',
    'filename' => 'birdfat-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdfat-lg_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdfat-lg_1.jpg',
    'filename' => 'birdfat-lg_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdfat-lg_2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdfat-lg_2.jpg',
    'filename' => 'birdfat-lg_2.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdfat-lg_3.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdfat-lg_3.jpg',
    'filename' => 'birdfat-lg_3.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdgreen-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdgreen-lg.jpg',
    'filename' => 'birdgreen-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdgreen-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdgreen-lg_0.jpg',
    'filename' => 'birdgreen-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdgreen-lg_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdgreen-lg_1.jpg',
    'filename' => 'birdgreen-lg_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdgreen-lg_2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdgreen-lg_2.jpg',
    'filename' => 'birdgreen-lg_2.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdretro-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdretro-lg.jpg',
    'filename' => 'birdretro-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdretro-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdretro-lg_0.jpg',
    'filename' => 'birdretro-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdsepia-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdsepia-lg.jpg',
    'filename' => 'birdsepia-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdsepia-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdsepia-lg_0.jpg',
    'filename' => 'birdsepia-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/birdsepia-lg_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/birdsepia-lg_1.jpg',
    'filename' => 'birdsepia-lg_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/butterfly-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/butterfly-lg.jpg',
    'filename' => 'butterfly-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/butterfly-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/butterfly-lg_0.jpg',
    'filename' => 'butterfly-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/butterfly-lg_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/butterfly-lg_1.jpg',
    'filename' => 'butterfly-lg_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/butterfly-lg_2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/butterfly-lg_2.jpg',
    'filename' => 'butterfly-lg_2.jpg',
  ),
  'public://designssquare_com/widget/gallery/flowers-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/flowers-lg.jpg',
    'filename' => 'flowers-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/flowers-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/flowers-lg_0.jpg',
    'filename' => 'flowers-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/flowers-lg_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/flowers-lg_1.jpg',
    'filename' => 'flowers-lg_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/flowers-lg_2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/flowers-lg_2.jpg',
    'filename' => 'flowers-lg_2.jpg',
  ),
  'public://designssquare_com/widget/gallery/flowers-lg_3.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/flowers-lg_3.jpg',
    'filename' => 'flowers-lg_3.jpg',
  ),
  'public://designssquare_com/widget/gallery/leaves-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/leaves-lg.jpg',
    'filename' => 'leaves-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/leaves-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/leaves-lg_0.jpg',
    'filename' => 'leaves-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/leaves-lg_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/leaves-lg_1.jpg',
    'filename' => 'leaves-lg_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/leaves-lg_2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/leaves-lg_2.jpg',
    'filename' => 'leaves-lg_2.jpg',
  ),
  'public://designssquare_com/widget/gallery/leaves-lg_3.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/leaves-lg_3.jpg',
    'filename' => 'leaves-lg_3.jpg',
  ),
  'public://designssquare_com/widget/gallery/leaves-lg_4.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/leaves-lg_4.jpg',
    'filename' => 'leaves-lg_4.jpg',
  ),
  'public://designssquare_com/widget/gallery/P1020079.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020079.JPG',
    'filename' => 'P1020079.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020082.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020082.JPG',
    'filename' => 'P1020082.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020083.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020083.JPG',
    'filename' => 'P1020083.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020084.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020084.JPG',
    'filename' => 'P1020084.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020087.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020087.JPG',
    'filename' => 'P1020087.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020089.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020089.JPG',
    'filename' => 'P1020089.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020089_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020089_0.JPG',
    'filename' => 'P1020089_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020090.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020090.JPG',
    'filename' => 'P1020090.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020095.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020095.JPG',
    'filename' => 'P1020095.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020096.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020096.JPG',
    'filename' => 'P1020096.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020099.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020099.JPG',
    'filename' => 'P1020099.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020100.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020100.JPG',
    'filename' => 'P1020100.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020100_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020100_0.JPG',
    'filename' => 'P1020100_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020101.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020101.JPG',
    'filename' => 'P1020101.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020102.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020102.JPG',
    'filename' => 'P1020102.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020103.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020103.JPG',
    'filename' => 'P1020103.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020104.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020104.JPG',
    'filename' => 'P1020104.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020105.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020105.JPG',
    'filename' => 'P1020105.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020108.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020108.JPG',
    'filename' => 'P1020108.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020109_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020109_0.JPG',
    'filename' => 'P1020109_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020112.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020112.JPG',
    'filename' => 'P1020112.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020113.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020113.JPG',
    'filename' => 'P1020113.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020113_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020113_0.JPG',
    'filename' => 'P1020113_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020124_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020124_0.JPG',
    'filename' => 'P1020124_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020125_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020125_0.JPG',
    'filename' => 'P1020125_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020126_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020126_0.JPG',
    'filename' => 'P1020126_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020127_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020127_0.JPG',
    'filename' => 'P1020127_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020127_0_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020127_0_0.JPG',
    'filename' => 'P1020127_0_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020128_0.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020128_0.JPG',
    'filename' => 'P1020128_0.JPG',
  ),
  'public://designssquare_com/widget/gallery/P1020129-rotated2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020129-rotated2.jpg',
    'filename' => 'P1020129-rotated2.jpg',
  ),
  'public://designssquare_com/widget/gallery/P1020143.JPG' => array(
    'uri' => 'public://designssquare_com/widget/gallery/P1020143.JPG',
    'filename' => 'P1020143.JPG',
  ),
  'public://designssquare_com/widget/gallery/slice.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/slice.jpg',
    'filename' => 'slice.jpg',
  ),
  'public://designssquare_com/widget/gallery/slice_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/slice_1.jpg',
    'filename' => 'slice_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/slice_2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/slice_2.jpg',
    'filename' => 'slice_2.jpg',
  ),
  'public://designssquare_com/widget/gallery/slice_3.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/slice_3.jpg',
    'filename' => 'slice_3.jpg',
  ),
  'public://designssquare_com/widget/gallery/slice_4.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/slice_4.jpg',
    'filename' => 'slice_4.jpg',
  ),
  'public://designssquare_com/widget/gallery/snail-lg.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/snail-lg.jpg',
    'filename' => 'snail-lg.jpg',
  ),
  'public://designssquare_com/widget/gallery/snail-lg_0.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/snail-lg_0.jpg',
    'filename' => 'snail-lg_0.jpg',
  ),
  'public://designssquare_com/widget/gallery/snail-lg_1.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/snail-lg_1.jpg',
    'filename' => 'snail-lg_1.jpg',
  ),
  'public://designssquare_com/widget/gallery/snail-lg_2.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/snail-lg_2.jpg',
    'filename' => 'snail-lg_2.jpg',
  ),
  'public://designssquare_com/widget/gallery/snail-lg_3.jpg' => array(
    'uri' => 'public://designssquare_com/widget/gallery/snail-lg_3.jpg',
    'filename' => 'snail-lg_3.jpg',
  ),
  'public://designssquare_com/widget/service/admin_11.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_11.png',
    'filename' => 'admin_11.png',
  ),
  'public://designssquare_com/widget/service/admin_2.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_2.png',
    'filename' => 'admin_2.png',
  ),
  'public://designssquare_com/widget/service/admin_3.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_3.png',
    'filename' => 'admin_3.png',
  ),
  'public://designssquare_com/widget/service/admin_3_0.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_3_0.png',
    'filename' => 'admin_3_0.png',
  ),
  'public://designssquare_com/widget/service/admin_3_1.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_3_1.png',
    'filename' => 'admin_3_1.png',
  ),
  'public://designssquare_com/widget/service/admin_3_2.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_3_2.png',
    'filename' => 'admin_3_2.png',
  ),
  'public://designssquare_com/widget/service/admin_4.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_4.png',
    'filename' => 'admin_4.png',
  ),
  'public://designssquare_com/widget/service/admin_4_0.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_4_0.png',
    'filename' => 'admin_4_0.png',
  ),
  'public://designssquare_com/widget/service/admin_4_1.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_4_1.png',
    'filename' => 'admin_4_1.png',
  ),
  'public://designssquare_com/widget/service/admin_6.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_6.png',
    'filename' => 'admin_6.png',
  ),
  'public://designssquare_com/widget/service/admin_9.png' => array(
    'uri' => 'public://designssquare_com/widget/service/admin_9.png',
    'filename' => 'admin_9.png',
  ),
  'public://designssquare_com/widget/service/Latvia-currency.jpg' => array(
    'uri' => 'public://designssquare_com/widget/service/Latvia-currency.jpg',
    'filename' => 'Latvia-currency.jpg',
  ),
  'public://designssquare_com/widget/service/latvian_symbol.png' => array(
    'uri' => 'public://designssquare_com/widget/service/latvian_symbol.png',
    'filename' => 'latvian_symbol.png',
  ),
  'public://designssquare_com/widget/service/latvian_symbol_0.png' => array(
    'uri' => 'public://designssquare_com/widget/service/latvian_symbol_0.png',
    'filename' => 'latvian_symbol_0.png',
  ),
  'public://designssquare_com_theme_blocks/assets/img/html5.png' => array(
    'uri' => 'public://designssquare_com_theme_blocks/assets/img/html5.png',
    'filename' => 'html5.png',
  ),
  'public://designssquare_com_theme_blocks/assets/img/html5_0.png' => array(
    'uri' => 'public://designssquare_com_theme_blocks/assets/img/html5_0.png',
    'filename' => 'html5_0.png',
  ),
  'public://designssquare_com_theme_blocks/assets/img/Latvia-currency.jpg' => array(
    'uri' => 'public://designssquare_com_theme_blocks/assets/img/Latvia-currency.jpg',
    'filename' => 'Latvia-currency.jpg',
  ),
  'public://designssquare_com_theme_builder/images/admin.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/admin.png',
    'filename' => 'admin.png',
  ),
  'public://designssquare_com_theme_builder/images/frame.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/frame.png',
    'filename' => 'frame.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/1.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/1.jpg',
    'filename' => '1.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/10.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/10.jpg',
    'filename' => '10.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/11.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/11.jpg',
    'filename' => '11.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/12.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/12.jpg',
    'filename' => '12.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/2.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/2.jpg',
    'filename' => '2.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/3.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/3.jpg',
    'filename' => '3.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/320.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/320.png',
    'filename' => '320.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/3201.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/3201.png',
    'filename' => '3201.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/3202.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/3202.png',
    'filename' => '3202.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/4.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/4.jpg',
    'filename' => '4.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/45.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/45.png',
    'filename' => '45.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/5.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/5.jpg',
    'filename' => '5.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/6.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/6.jpg',
    'filename' => '6.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/7.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/7.jpg',
    'filename' => '7.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/71.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/71.jpg',
    'filename' => '71.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/8.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/8.jpg',
    'filename' => '8.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/9.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/9.jpg',
    'filename' => '9.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/admin.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/admin.png',
    'filename' => 'admin.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/aj_300x250_v1.gif' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/aj_300x250_v1.gif',
    'filename' => 'aj_300x250_v1.gif',
  ),
  'public://designssquare_com_theme_builder/images/gallery/Anchor_v1_preview2-880x461.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/Anchor_v1_preview2-880x461.png',
    'filename' => 'Anchor_v1_preview2-880x461.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/avatar-2.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/avatar-2.png',
    'filename' => 'avatar-2.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/avatar.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/avatar.jpg',
    'filename' => 'avatar.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/BC.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/BC.jpg',
    'filename' => 'BC.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/bg2.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/bg2.jpg',
    'filename' => 'bg2.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/blur.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/blur.jpg',
    'filename' => 'blur.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/box-blur.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/box-blur.png',
    'filename' => 'box-blur.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/box-normal.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/box-normal.png',
    'filename' => 'box-normal.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/bs-docs-responsive-illustrations.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/bs-docs-responsive-illustrations.png',
    'filename' => 'bs-docs-responsive-illustrations.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/frame.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/frame.png',
    'filename' => 'frame.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/hand-black2.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/hand-black2.png',
    'filename' => 'hand-black2.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/html5.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/html5.png',
    'filename' => 'html5.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/ipad.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/ipad.png',
    'filename' => 'ipad.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/ipad1.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/ipad1.png',
    'filename' => 'ipad1.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/ipad21.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/ipad21.png',
    'filename' => 'ipad21.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/land.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/land.jpg',
    'filename' => 'land.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/logo-footer.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/logo-footer.png',
    'filename' => 'logo-footer.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/newone.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/newone.jpg',
    'filename' => 'newone.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/oi-80.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/oi-80.jpg',
    'filename' => 'oi-80.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/retro_stripe1.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/retro_stripe1.png',
    'filename' => 'retro_stripe1.png',
  ),
  'public://designssquare_com_theme_builder/images/gallery/slide11.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/slide11.jpg',
    'filename' => 'slide11.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/slide2.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/slide2.jpg',
    'filename' => 'slide2.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/slide31.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/slide31.jpg',
    'filename' => 'slide31.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/slide_1.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/slide_1.jpg',
    'filename' => 'slide_1.jpg',
  ),
  'public://designssquare_com_theme_builder/images/gallery/tranc.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/gallery/tranc.png',
    'filename' => 'tranc.png',
  ),
  'public://designssquare_com_theme_builder/images/ipad.png' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/ipad.png',
    'filename' => 'ipad.png',
  ),
  'public://designssquare_com_theme_builder/images/portrait/1.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/portrait/1.jpg',
    'filename' => '1.jpg',
  ),
  'public://designssquare_com_theme_builder/images/portrait/2.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/portrait/2.jpg',
    'filename' => '2.jpg',
  ),
  'public://designssquare_com_theme_builder/images/portrait/3.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/portrait/3.jpg',
    'filename' => '3.jpg',
  ),
  'public://designssquare_com_theme_builder/images/portrait/4-581x402.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/portrait/4-581x402.jpg',
    'filename' => '4-581x402.jpg',
  ),
  'public://designssquare_com_theme_builder/images/portrait/4.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/portrait/4.jpg',
    'filename' => '4.jpg',
  ),
  'public://designssquare_com_theme_builder/images/portrait/5.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/portrait/5.jpg',
    'filename' => '5.jpg',
  ),
  'public://designssquare_com_theme_builder/images/portrait/6.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/portrait/6.jpg',
    'filename' => '6.jpg',
  ),
  'public://designssquare_com_theme_builder/images/services-1.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/services-1.jpg',
    'filename' => 'services-1.jpg',
  ),
  'public://designssquare_com_theme_builder/images/services-2.jpg' => array(
    'uri' => 'public://designssquare_com_theme_builder/images/services-2.jpg',
    'filename' => 'services-2.jpg',
  ),
  'public://sites/.DS_Store' => array(
    'uri' => 'public://sites/.DS_Store',
    'filename' => '.DS_Store',
  ),
  'public://sites/all/.DS_Store' => array(
    'uri' => 'public://sites/all/.DS_Store',
    'filename' => '.DS_Store',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/1.jpg',
    'filename' => '1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/11.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/11.jpg',
    'filename' => '11.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/131117remittances.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/131117remittances.jpg',
    'filename' => '131117remittances.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_0.jpg',
    'filename' => '1_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_1.jpg',
    'filename' => '1_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_2.jpg',
    'filename' => '1_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_3.jpg',
    'filename' => '1_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_4.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/1_4.jpg',
    'filename' => '1_4.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/2.jpg',
    'filename' => '2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_0.jpg',
    'filename' => '2_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_1.jpg',
    'filename' => '2_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_2.jpg',
    'filename' => '2_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/2_3.jpg',
    'filename' => '2_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/3.jpg',
    'filename' => '3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_0.jpg',
    'filename' => '3_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_1.jpg',
    'filename' => '3_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_2.jpg',
    'filename' => '3_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/3_3.jpg',
    'filename' => '3_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4-581x402.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4-581x402.jpg',
    'filename' => '4-581x402.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4.jpg',
    'filename' => '4.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_0.jpg',
    'filename' => '4_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_1.jpg',
    'filename' => '4_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_2.jpg',
    'filename' => '4_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_3.jpg',
    'filename' => '4_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_4.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_4.jpg',
    'filename' => '4_4.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_5.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/4_5.jpg',
    'filename' => '4_5.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/5.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/5.jpg',
    'filename' => '5.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/5_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/5_0.jpg',
    'filename' => '5_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/5_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/5_1.jpg',
    'filename' => '5_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/6.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/6.jpg',
    'filename' => '6.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_0.jpg',
    'filename' => '6_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_1.jpg',
    'filename' => '6_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_2.jpg',
    'filename' => '6_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/6_3.jpg',
    'filename' => '6_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/7.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/7.jpg',
    'filename' => '7.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/7_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/7_0.jpg',
    'filename' => '7_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/7_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/7_1.jpg',
    'filename' => '7_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8.jpg',
    'filename' => '8.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_0.jpg',
    'filename' => '8_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_1.jpg',
    'filename' => '8_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_2.jpg',
    'filename' => '8_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_3.jpg',
    'filename' => '8_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_4.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_4.jpg',
    'filename' => '8_4.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_5.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_5.jpg',
    'filename' => '8_5.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_6.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_6.jpg',
    'filename' => '8_6.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_7.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_7.jpg',
    'filename' => '8_7.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_8.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_8.jpg',
    'filename' => '8_8.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_9.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/8_9.jpg',
    'filename' => '8_9.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/9.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/9.jpg',
    'filename' => '9.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/9_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/9_0.jpg',
    'filename' => '9_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin.png',
    'filename' => 'admin.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_0.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_0.png',
    'filename' => 'admin_0.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_1.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_1.png',
    'filename' => 'admin_1.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_10.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_10.png',
    'filename' => 'admin_10.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_11.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_11.png',
    'filename' => 'admin_11.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_2.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_2.png',
    'filename' => 'admin_2.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_3.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_3.png',
    'filename' => 'admin_3.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_4.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_4.png',
    'filename' => 'admin_4.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_5.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_5.png',
    'filename' => 'admin_5.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_6.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_6.png',
    'filename' => 'admin_6.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_7.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_7.png',
    'filename' => 'admin_7.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_8.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_8.png',
    'filename' => 'admin_8.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_9.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/admin_9.png',
    'filename' => 'admin_9.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/Allegro-from-Duet-in-Major.mp3' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/Allegro-from-Duet-in-Major.mp3',
    'filename' => 'Allegro-from-Duet-in-Major.mp3',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/Allegro-from-Duet-in-Major_0.mp3' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/Allegro-from-Duet-in-Major_0.mp3',
    'filename' => 'Allegro-from-Duet-in-Major_0.mp3',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/blur.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/blur.jpg',
    'filename' => 'blur.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/dual_citizenship.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/dual_citizenship.jpg',
    'filename' => 'dual_citizenship.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/dziemas_svetki.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/dziemas_svetki.jpg',
    'filename' => 'dziemas_svetki.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/frame.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/frame.png',
    'filename' => 'frame.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/frame_0.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/frame_0.png',
    'filename' => 'frame_0.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/H264_test2_Talkinghead_mp4_480x320.mp4' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/H264_test2_Talkinghead_mp4_480x320.mp4',
    'filename' => 'H264_test2_Talkinghead_mp4_480x320.mp4',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/H264_test2_Talkinghead_mp4_480x320_0.mp4' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/H264_test2_Talkinghead_mp4_480x320_0.mp4',
    'filename' => 'H264_test2_Talkinghead_mp4_480x320_0.mp4',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/H264_test2_Talkinghead_mp4_480x320_0_0.mp4' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/H264_test2_Talkinghead_mp4_480x320_0_0.mp4',
    'filename' => 'H264_test2_Talkinghead_mp4_480x320_0_0.mp4',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/html5.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/html5.png',
    'filename' => 'html5.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/ipad.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/ipad.png',
    'filename' => 'ipad.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/ipad_0.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/ipad_0.png',
    'filename' => 'ipad_0.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/ipad_1.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/ipad_1.png',
    'filename' => 'ipad_1.png',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/Latvia-currency_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/Latvia-currency_0.jpg',
    'filename' => 'Latvia-currency_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/newone.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/newone.jpg',
    'filename' => 'newone.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020079.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020079.JPG',
    'filename' => 'P1020079.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020079_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020079_0.JPG',
    'filename' => 'P1020079_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020082.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020082.JPG',
    'filename' => 'P1020082.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020083.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020083.JPG',
    'filename' => 'P1020083.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020084.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020084.JPG',
    'filename' => 'P1020084.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020085.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020085.JPG',
    'filename' => 'P1020085.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020087.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020087.JPG',
    'filename' => 'P1020087.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020089.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020089.JPG',
    'filename' => 'P1020089.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020090.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020090.JPG',
    'filename' => 'P1020090.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020095.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020095.JPG',
    'filename' => 'P1020095.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020096.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020096.JPG',
    'filename' => 'P1020096.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020099.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020099.JPG',
    'filename' => 'P1020099.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020100.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020100.JPG',
    'filename' => 'P1020100.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020100_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020100_0.JPG',
    'filename' => 'P1020100_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020101.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020101.JPG',
    'filename' => 'P1020101.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020102.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020102.JPG',
    'filename' => 'P1020102.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020103.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020103.JPG',
    'filename' => 'P1020103.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020104.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020104.JPG',
    'filename' => 'P1020104.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020105.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020105.JPG',
    'filename' => 'P1020105.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020106.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020106.JPG',
    'filename' => 'P1020106.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020108.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020108.JPG',
    'filename' => 'P1020108.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020109_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020109_0.JPG',
    'filename' => 'P1020109_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020112.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020112.JPG',
    'filename' => 'P1020112.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020113.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020113.JPG',
    'filename' => 'P1020113.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020113_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020113_0.JPG',
    'filename' => 'P1020113_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020114.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020114.JPG',
    'filename' => 'P1020114.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020116_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020116_0.JPG',
    'filename' => 'P1020116_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020118_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020118_0.JPG',
    'filename' => 'P1020118_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020121.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020121.JPG',
    'filename' => 'P1020121.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020123.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020123.JPG',
    'filename' => 'P1020123.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020124_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020124_0.JPG',
    'filename' => 'P1020124_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020125_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020125_0.JPG',
    'filename' => 'P1020125_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020126_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020126_0.JPG',
    'filename' => 'P1020126_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020127_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020127_0.JPG',
    'filename' => 'P1020127_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020127_1.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020127_1.JPG',
    'filename' => 'P1020127_1.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020128_0.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020128_0.JPG',
    'filename' => 'P1020128_0.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020129-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020129-rotated2.jpg',
    'filename' => 'P1020129-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020130-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020130-rotated2.jpg',
    'filename' => 'P1020130-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020131-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020131-rotated2.jpg',
    'filename' => 'P1020131-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020132-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020132-rotated2.jpg',
    'filename' => 'P1020132-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020134-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020134-rotated2.jpg',
    'filename' => 'P1020134-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020135-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020135-rotated2.jpg',
    'filename' => 'P1020135-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020139.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020139.JPG',
    'filename' => 'P1020139.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020141-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020141-rotated2.jpg',
    'filename' => 'P1020141-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020143.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020143.JPG',
    'filename' => 'P1020143.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020145.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020145.JPG',
    'filename' => 'P1020145.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020147.JPG' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020147.JPG',
    'filename' => 'P1020147.JPG',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020150-rotated2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/P1020150-rotated2.jpg',
    'filename' => 'P1020150-rotated2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/services-1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/services-1.jpg',
    'filename' => 'services-1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/services-2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/services-2.jpg',
    'filename' => 'services-2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/Westminster-20130918-00335.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/Westminster-20130918-00335.jpg',
    'filename' => 'Westminster-20130918-00335.jpg',
  ),
  'public://sites/all/modules/designssquare_com_site_loam/assets/data/Westminster-20130918-00335_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_site_loam/assets/data/Westminster-20130918-00335_0.jpg',
    'filename' => 'Westminster-20130918-00335_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/1-bg.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/1-bg.jpg',
    'filename' => '1-bg.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/1.jpg',
    'filename' => '1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/1_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/1_0.jpg',
    'filename' => '1_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/1_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/1_1.jpg',
    'filename' => '1_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/1_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/1_2.jpg',
    'filename' => '1_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/1_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/1_3.jpg',
    'filename' => '1_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/1_4.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/1_4.jpg',
    'filename' => '1_4.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/2-bg.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/2-bg.jpg',
    'filename' => '2-bg.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/2.jpg',
    'filename' => '2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/2_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/2_0.jpg',
    'filename' => '2_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/2_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/2_1.jpg',
    'filename' => '2_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/2_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/2_2.jpg',
    'filename' => '2_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/2_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/2_3.jpg',
    'filename' => '2_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/3-bg.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/3-bg.jpg',
    'filename' => '3-bg.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/3.jpg',
    'filename' => '3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/3_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/3_0.jpg',
    'filename' => '3_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/3_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/3_1.jpg',
    'filename' => '3_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/3_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/3_2.jpg',
    'filename' => '3_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/3_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/3_3.jpg',
    'filename' => '3_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4-581x402.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4-581x402.jpg',
    'filename' => '4-581x402.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4.jpg',
    'filename' => '4.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4_0.jpg',
    'filename' => '4_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4_1.jpg',
    'filename' => '4_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4_2.jpg',
    'filename' => '4_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4_3.jpg',
    'filename' => '4_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4_4.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4_4.jpg',
    'filename' => '4_4.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/4_5.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/4_5.jpg',
    'filename' => '4_5.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/5.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/5.jpg',
    'filename' => '5.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/5_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/5_0.jpg',
    'filename' => '5_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/5_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/5_1.jpg',
    'filename' => '5_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/6.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/6.jpg',
    'filename' => '6.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/6_0.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/6_0.jpg',
    'filename' => '6_0.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/6_1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/6_1.jpg',
    'filename' => '6_1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/6_2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/6_2.jpg',
    'filename' => '6_2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/6_3.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/6_3.jpg',
    'filename' => '6_3.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/7.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/7.jpg',
    'filename' => '7.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/9.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/9.jpg',
    'filename' => '9.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/admin.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/admin.png',
    'filename' => 'admin.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/admin_0.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/admin_0.png',
    'filename' => 'admin_0.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/admin_1.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/admin_1.png',
    'filename' => 'admin_1.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/frame.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/frame.png',
    'filename' => 'frame.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/frame_0.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/frame_0.png',
    'filename' => 'frame_0.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/html5.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/html5.png',
    'filename' => 'html5.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/ipad.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/ipad.png',
    'filename' => 'ipad.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/ipad_0.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/ipad_0.png',
    'filename' => 'ipad_0.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/ipad_1.png' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/ipad_1.png',
    'filename' => 'ipad_1.png',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/newone.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/newone.jpg',
    'filename' => 'newone.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/services-1.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/services-1.jpg',
    'filename' => 'services-1.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/services-2.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/services-2.jpg',
    'filename' => 'services-2.jpg',
  ),
  'public://sites/all/modules/designssquare_com_theme_builder/assets/Westminster-20130918-00335.jpg' => array(
    'uri' => 'public://sites/all/modules/designssquare_com_theme_builder/assets/Westminster-20130918-00335.jpg',
    'filename' => 'Westminster-20130918-00335.jpg',
  ),
  'public://slider/revolution/img/1-l1.png' => array(
    'uri' => 'public://slider/revolution/img/1-l1.png',
    'filename' => '1-l1.png',
  ),
  'public://slider/revolution/img/1-l2.png' => array(
    'uri' => 'public://slider/revolution/img/1-l2.png',
    'filename' => '1-l2.png',
  ),
  'public://slider/revolution/img/1-l3.png' => array(
    'uri' => 'public://slider/revolution/img/1-l3.png',
    'filename' => '1-l3.png',
  ),
  'public://slider/revolution/img/1-l4.png' => array(
    'uri' => 'public://slider/revolution/img/1-l4.png',
    'filename' => '1-l4.png',
  ),
  'public://slider/revolution/img/1-l5.png' => array(
    'uri' => 'public://slider/revolution/img/1-l5.png',
    'filename' => '1-l5.png',
  ),
  'public://slider/revolution/img/1-l6.png' => array(
    'uri' => 'public://slider/revolution/img/1-l6.png',
    'filename' => '1-l6.png',
  ),
  'public://slider/revolution/img/1.jpg' => array(
    'uri' => 'public://slider/revolution/img/1.jpg',
    'filename' => '1.jpg',
  ),
  'public://slider/revolution/img/2-10.png' => array(
    'uri' => 'public://slider/revolution/img/2-10.png',
    'filename' => '2-10.png',
  ),
  'public://slider/revolution/img/2-10_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-10_0.png',
    'filename' => '2-10_0.png',
  ),
  'public://slider/revolution/img/2-11.png' => array(
    'uri' => 'public://slider/revolution/img/2-11.png',
    'filename' => '2-11.png',
  ),
  'public://slider/revolution/img/2-11_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-11_0.png',
    'filename' => '2-11_0.png',
  ),
  'public://slider/revolution/img/2-12.png' => array(
    'uri' => 'public://slider/revolution/img/2-12.png',
    'filename' => '2-12.png',
  ),
  'public://slider/revolution/img/2-12_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-12_0.png',
    'filename' => '2-12_0.png',
  ),
  'public://slider/revolution/img/2-l1.jpg' => array(
    'uri' => 'public://slider/revolution/img/2-l1.jpg',
    'filename' => '2-l1.jpg',
  ),
  'public://slider/revolution/img/2-l1_0.jpg' => array(
    'uri' => 'public://slider/revolution/img/2-l1_0.jpg',
    'filename' => '2-l1_0.jpg',
  ),
  'public://slider/revolution/img/2-l21.png' => array(
    'uri' => 'public://slider/revolution/img/2-l21.png',
    'filename' => '2-l21.png',
  ),
  'public://slider/revolution/img/2-l21_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l21_0.png',
    'filename' => '2-l21_0.png',
  ),
  'public://slider/revolution/img/2-l3.png' => array(
    'uri' => 'public://slider/revolution/img/2-l3.png',
    'filename' => '2-l3.png',
  ),
  'public://slider/revolution/img/2-l3_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l3_0.png',
    'filename' => '2-l3_0.png',
  ),
  'public://slider/revolution/img/2-l4.png' => array(
    'uri' => 'public://slider/revolution/img/2-l4.png',
    'filename' => '2-l4.png',
  ),
  'public://slider/revolution/img/2-l4_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l4_0.png',
    'filename' => '2-l4_0.png',
  ),
  'public://slider/revolution/img/2-l5.png' => array(
    'uri' => 'public://slider/revolution/img/2-l5.png',
    'filename' => '2-l5.png',
  ),
  'public://slider/revolution/img/2-l5_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l5_0.png',
    'filename' => '2-l5_0.png',
  ),
  'public://slider/revolution/img/2-l6.png' => array(
    'uri' => 'public://slider/revolution/img/2-l6.png',
    'filename' => '2-l6.png',
  ),
  'public://slider/revolution/img/2-l6_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l6_0.png',
    'filename' => '2-l6_0.png',
  ),
  'public://slider/revolution/img/2-l7.png' => array(
    'uri' => 'public://slider/revolution/img/2-l7.png',
    'filename' => '2-l7.png',
  ),
  'public://slider/revolution/img/2-l7_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l7_0.png',
    'filename' => '2-l7_0.png',
  ),
  'public://slider/revolution/img/2-l8.png' => array(
    'uri' => 'public://slider/revolution/img/2-l8.png',
    'filename' => '2-l8.png',
  ),
  'public://slider/revolution/img/2-l8_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l8_0.png',
    'filename' => '2-l8_0.png',
  ),
  'public://slider/revolution/img/2-l9.png' => array(
    'uri' => 'public://slider/revolution/img/2-l9.png',
    'filename' => '2-l9.png',
  ),
  'public://slider/revolution/img/2-l9_0.png' => array(
    'uri' => 'public://slider/revolution/img/2-l9_0.png',
    'filename' => '2-l9_0.png',
  ),
  'public://slider/revolution/img/3-l1.png' => array(
    'uri' => 'public://slider/revolution/img/3-l1.png',
    'filename' => '3-l1.png',
  ),
  'public://slider/revolution/img/3-l2.png' => array(
    'uri' => 'public://slider/revolution/img/3-l2.png',
    'filename' => '3-l2.png',
  ),
  'public://slider/revolution/img/3-l3.png' => array(
    'uri' => 'public://slider/revolution/img/3-l3.png',
    'filename' => '3-l3.png',
  ),
  'public://slider/revolution/img/7_1.jpg' => array(
    'uri' => 'public://slider/revolution/img/7_1.jpg',
    'filename' => '7_1.jpg',
  ),
  'public://slider/revolution/img/8.jpg' => array(
    'uri' => 'public://slider/revolution/img/8.jpg',
    'filename' => '8.jpg',
  ),
  'public://slider/revolution/img/8_0.jpg' => array(
    'uri' => 'public://slider/revolution/img/8_0.jpg',
    'filename' => '8_0.jpg',
  ),
  'public://slider/revolution/img/8_7.jpg' => array(
    'uri' => 'public://slider/revolution/img/8_7.jpg',
    'filename' => '8_7.jpg',
  ),
  'public://slider/revolution/img/admin_0.png' => array(
    'uri' => 'public://slider/revolution/img/admin_0.png',
    'filename' => 'admin_0.png',
  ),
  'public://slider/revolution/img/admin_0_0.png' => array(
    'uri' => 'public://slider/revolution/img/admin_0_0.png',
    'filename' => 'admin_0_0.png',
  ),
  'public://slider/revolution/img/admin_1.png' => array(
    'uri' => 'public://slider/revolution/img/admin_1.png',
    'filename' => 'admin_1.png',
  ),
  'public://slider/revolution/img/dailesTeatris1.png' => array(
    'uri' => 'public://slider/revolution/img/dailesTeatris1.png',
    'filename' => 'dailesTeatris1.png',
  ),
  'public://slider/revolution/img/dailesTeatris1_300x288.png' => array(
    'uri' => 'public://slider/revolution/img/dailesTeatris1_300x288.png',
    'filename' => 'dailesTeatris1_300x288.png',
  ),
  'public://slider/revolution/img/dailesTeatris2.png' => array(
    'uri' => 'public://slider/revolution/img/dailesTeatris2.png',
    'filename' => 'dailesTeatris2.png',
  ),
  'public://slider/revolution/img/dailesTeatris2_300x288.png' => array(
    'uri' => 'public://slider/revolution/img/dailesTeatris2_300x288.png',
    'filename' => 'dailesTeatris2_300x288.png',
  ),
  'public://slider/revolution/img/dream-team_2.png' => array(
    'uri' => 'public://slider/revolution/img/dream-team_2.png',
    'filename' => 'dream-team_2.png',
  ),
  'public://slider/revolution/img/hand-black2.png' => array(
    'uri' => 'public://slider/revolution/img/hand-black2.png',
    'filename' => 'hand-black2.png',
  ),
  'public://slider/revolution/img/LOAM Valde 2.jpg' => array(
    'uri' => 'public://slider/revolution/img/LOAM Valde 2.jpg',
    'filename' => 'LOAM Valde 2.jpg',
  ),
  'public://slider/revolution/img/LOAM-Valde-2_800x300.png' => array(
    'uri' => 'public://slider/revolution/img/LOAM-Valde-2_800x300.png',
    'filename' => 'LOAM-Valde-2_800x300.png',
  ),
  'public://slider/revolution/img/LOAM-Valde-2_800x300_0.png' => array(
    'uri' => 'public://slider/revolution/img/LOAM-Valde-2_800x300_0.png',
    'filename' => 'LOAM-Valde-2_800x300_0.png',
  ),
  'public://slider/revolution/img/LOAM-Valde-2_800x300_1.png' => array(
    'uri' => 'public://slider/revolution/img/LOAM-Valde-2_800x300_1.png',
    'filename' => 'LOAM-Valde-2_800x300_1.png',
  ),
  'public://slider/revolution/img/LOAM-Valde-2_900x400.png' => array(
    'uri' => 'public://slider/revolution/img/LOAM-Valde-2_900x400.png',
    'filename' => 'LOAM-Valde-2_900x400.png',
  ),
  'public://slider/revolution/img/LOAM-Valde-2_950x450.png' => array(
    'uri' => 'public://slider/revolution/img/LOAM-Valde-2_950x450.png',
    'filename' => 'LOAM-Valde-2_950x450.png',
  ),
  'public://slider/revolution/img/man_woman_dancing.jpg' => array(
    'uri' => 'public://slider/revolution/img/man_woman_dancing.jpg',
    'filename' => 'man_woman_dancing.jpg',
  ),
  'public://slider/revolution/img/P1020112_1.JPG' => array(
    'uri' => 'public://slider/revolution/img/P1020112_1.JPG',
    'filename' => 'P1020112_1.JPG',
  ),
  'public://slider/revolution/img/P1020112_3.JPG' => array(
    'uri' => 'public://slider/revolution/img/P1020112_3.JPG',
    'filename' => 'P1020112_3.JPG',
  ),
  'public://slider/revolution/img/P1020112_4.JPG' => array(
    'uri' => 'public://slider/revolution/img/P1020112_4.JPG',
    'filename' => 'P1020112_4.JPG',
  ),
  'public://slider/revolution/img/P1020112_5.JPG' => array(
    'uri' => 'public://slider/revolution/img/P1020112_5.JPG',
    'filename' => 'P1020112_5.JPG',
  ),
  'public://slider/revolution/img/paris_dejo.jpg' => array(
    'uri' => 'public://slider/revolution/img/paris_dejo.jpg',
    'filename' => 'paris_dejo.jpg',
  ),
  'public://slider/revolution/img/paris_dejo_0.jpg' => array(
    'uri' => 'public://slider/revolution/img/paris_dejo_0.jpg',
    'filename' => 'paris_dejo_0.jpg',
  ),
  'public://slider/revolution/img/rigas-sargi.jpg' => array(
    'uri' => 'public://slider/revolution/img/rigas-sargi.jpg',
    'filename' => 'rigas-sargi.jpg',
  ),
  'public://slider/revolution/img/sieviete_sarkana.JPG' => array(
    'uri' => 'public://slider/revolution/img/sieviete_sarkana.JPG',
    'filename' => 'sieviete_sarkana.JPG',
  ),
  'public://slider/revolution/img/sieviete_sarkana_0.JPG' => array(
    'uri' => 'public://slider/revolution/img/sieviete_sarkana_0.JPG',
    'filename' => 'sieviete_sarkana_0.JPG',
  ),
  'public://slider/revolution/img/women_red_dresss.JPG' => array(
    'uri' => 'public://slider/revolution/img/women_red_dresss.JPG',
    'filename' => 'women_red_dresss.JPG',
  ),
  'public://slider/revolution/img/ziedojums_15.png' => array(
    'uri' => 'public://slider/revolution/img/ziedojums_15.png',
    'filename' => 'ziedojums_15.png',
  ),
  'public://slider/revolution/img/ziedojums_15_2xless.png' => array(
    'uri' => 'public://slider/revolution/img/ziedojums_15_2xless.png',
    'filename' => 'ziedojums_15_2xless.png',
  ),
  'public://slider/revolution/main-img/1-bg.jpg' => array(
    'uri' => 'public://slider/revolution/main-img/1-bg.jpg',
    'filename' => '1-bg.jpg',
  ),
  'public://slider/revolution/main-img/3-bg.jpg' => array(
    'uri' => 'public://slider/revolution/main-img/3-bg.jpg',
    'filename' => '3-bg.jpg',
  ),
  'public://slider/revolution/main-img/8_4.jpg' => array(
    'uri' => 'public://slider/revolution/main-img/8_4.jpg',
    'filename' => '8_4.jpg',
  ),
  'public://slider/revolution/main-img/P1020112.JPG' => array(
    'uri' => 'public://slider/revolution/main-img/P1020112.JPG',
    'filename' => 'P1020112.JPG',
  ),
  'public://slider/revolution/main-img/P1020112_0.JPG' => array(
    'uri' => 'public://slider/revolution/main-img/P1020112_0.JPG',
    'filename' => 'P1020112_0.JPG',
  ),
  'public://slider/revolution/main-img/P1020112_1.JPG' => array(
    'uri' => 'public://slider/revolution/main-img/P1020112_1.JPG',
    'filename' => 'P1020112_1.JPG',
  ),
  'public://slider/revolution/main-img/P1020112_2.JPG' => array(
    'uri' => 'public://slider/revolution/main-img/P1020112_2.JPG',
    'filename' => 'P1020112_2.JPG',
  ),
  'public://slider/revolution/main-img/P1020112_3.JPG' => array(
    'uri' => 'public://slider/revolution/main-img/P1020112_3.JPG',
    'filename' => 'P1020112_3.JPG',
  ),
  'public://slider/revolution/main-img/P1020112_4.JPG' => array(
    'uri' => 'public://slider/revolution/main-img/P1020112_4.JPG',
    'filename' => 'P1020112_4.JPG',
  ),
  'public://slider/revolution/main-img/retro_stripe_bg.png' => array(
    'uri' => 'public://slider/revolution/main-img/retro_stripe_bg.png',
    'filename' => 'retro_stripe_bg.png',
  ),
  'public://slider/revolution/main-img/retro_stripe_bg_0.png' => array(
    'uri' => 'public://slider/revolution/main-img/retro_stripe_bg_0.png',
    'filename' => 'retro_stripe_bg_0.png',
  ),
  'public://slider/revolution/main-img/retro_stripe_bg_1.png' => array(
    'uri' => 'public://slider/revolution/main-img/retro_stripe_bg_1.png',
    'filename' => 'retro_stripe_bg_1.png',
  ),
  'public://slider/revolution/main-img/retro_stripe_bg_2.png' => array(
    'uri' => 'public://slider/revolution/main-img/retro_stripe_bg_2.png',
    'filename' => 'retro_stripe_bg_2.png',
  ),
  'public://slider/revolution/main-img/retro_stripe_bg_3.png' => array(
    'uri' => 'public://slider/revolution/main-img/retro_stripe_bg_3.png',
    'filename' => 'retro_stripe_bg_3.png',
  ),
);
return $content_assets;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function esignssquare_com_site_loam_data_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function esignssquare_com_site_loam_data_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_menu_alias_default_settings().
 */
function esignssquare_com_site_loam_data_menu_alias_default_settings() {
$menu_alias = array();

$menu_alias = array(
  'main-menu' => array(
    'definition' => array(
      'menu_name' => 'main-menu',
      'title' => 'Main menu',
      'description' => 'The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.',
    ),
    'links' => array(
      'sākums-latviesu-organizāciju-apvieniba-minesotā' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
        'link_title' => 'Sākums',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -50,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-kalendārs/gads' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/gads',
        'link_title' => 'Gads',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -50,
        'depth' => 2,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'p2' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/gads',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-kalendārs/mēnesis' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/mēnesis',
        'link_title' => 'Mēnesis',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -49,
        'depth' => 2,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'p2' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/mēnesis',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_title' => 'LOAM',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 1,
        'expanded' => 1,
        'weight' => -49,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-kalendārs' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'link_title' => 'Kalendārs',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 1,
        'expanded' => 1,
        'weight' => -48,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-kalendārs/nedēļa' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/nedēļa',
        'link_title' => 'Nedēļa',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -48,
        'depth' => 2,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'p2' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/nedēļa',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-avīze' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-avīze',
        'link_title' => 'Avīze',
        'options' => array(
          'attributes' => array(),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 1,
        'weight' => -47,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-avīze',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-kalendārs/diena' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/diena',
        'link_title' => 'Diena',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -47,
        'depth' => 2,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'p2' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs/diena',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-foto-galerijas' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-foto-galerijas',
        'link_title' => 'Foto Galerijas',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -46,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-foto-galerijas',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/kontakts' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'content/kontakts',
        'link_title' => 'Kontakts',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -45,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'content/kontakts',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/selga-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/selga-0',
        'link_title' => 'SELGA',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/selga-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/lk-sabiedrība-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/lk-sabiedrība-0',
        'link_title' => 'LK Sabiedrība',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/lk-sabiedrība-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/teiksma-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/teiksma-0',
        'link_title' => 'Teiksma',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/teiksma-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/sp-latviešu-katoļu-draudze-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/sp-latviešu-katoļu-draudze-0',
        'link_title' => 'SP Latviešu katoļu draudze',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/sp-latviešu-katoļu-draudze-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/perkonītis-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/perkonītis-0',
        'link_title' => 'Perkonītis',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/perkonītis-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/daugavas-vanagi-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/daugavas-vanagi-0',
        'link_title' => 'Daugavas Vanagi',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/daugavas-vanagi-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/msp-draudze-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/msp-draudze-0',
        'link_title' => 'MSP DRAUDZE',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/msp-draudze-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/latviešu-skola-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/latviešu-skola-0',
        'link_title' => 'Latviešu Skola',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/latviešu-skola-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/mspd-koris-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/mspd-koris-0',
        'link_title' => 'MSPD Koris',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/mspd-koris-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/akadēmiskā-kopa-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/akadēmiskā-kopa-0',
        'link_title' => 'Akadēmiskā Kopa',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/akadēmiskā-kopa-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/tarts-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/tarts-0',
        'link_title' => 'TARTS',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/tarts-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/kkm-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/kkm-0',
        'link_title' => 'KKM',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/kkm-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/mkgpf-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/mkgpf-0',
        'link_title' => 'MKGPF',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/mkgpf-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/latviešu-koncertapvienība-mn-0' => array(
        'menu_name' => 'main-menu',
        'plid' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'link_path' => 'content/latviešu-koncertapvienība-mn-0',
        'link_title' => 'Latviešu Koncertapvienība MN',
        'options' => array(),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 2,
        'customized' => 0,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-visas-organizācijas',
        'p2' => 'content/latviešu-koncertapvienība-mn-0',
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
    ),
  ),
  'menu-footer-menu' => array(
    'definition' => array(
      'menu_name' => 'menu-footer-menu',
      'title' => 'Footer Menu',
      'description' => 'menu at the footer',
    ),
    'links' => array(
      'latviešu-organizācijas-apvienība-minesotā-kalendārs' => array(
        'menu_name' => 'menu-footer-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'link_title' => 'Kalendārs',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -49,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-kalendārs',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-avīze' => array(
        'menu_name' => 'menu-footer-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-avīze',
        'link_title' => 'Avīze',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -48,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-avīze',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā-foto-galerijas' => array(
        'menu_name' => 'menu-footer-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā-foto-galerijas',
        'link_title' => 'Foto Galerijas',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -47,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā-foto-galerijas',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'content/kontakts' => array(
        'menu_name' => 'menu-footer-menu',
        'plid' => 0,
        'link_path' => 'content/kontakts',
        'link_title' => 'Kontakts',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => -46,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'content/kontakts',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'sākums-latviesu-organizāciju-apvieniba-minesotā' => array(
        'menu_name' => 'menu-footer-menu',
        'plid' => 0,
        'link_path' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
        'link_title' => 'Sākums',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
    ),
  ),
);
return $menu_alias;
}

/**
 * Implements hook_strongarm_override_default_settings().
 */
function esignssquare_com_site_loam_data_strongarm_override_default_settings() {
$strongarm_override = array();

$strongarm_override[] = array(
  'name' => 'site_403',
  'value' => 'user',
);
$strongarm_override[] = array(
  'name' => 'site_404',
  'value' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
);
$strongarm_override[] = array(
  'name' => 'site_frontpage',
  'value' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
);
$strongarm_override[] = array(
  'name' => 'site_name',
  'value' => 'LOAM',
);
$strongarm_override[] = array(
  'name' => 'site_slogan',
  'value' => 'apvienot latviešu organizācijas kopējam kultūras and labdarības darbam',
);
return $strongarm_override;
}

/**
 * Implements hook_variable_assets_default_settings().
 */
function esignssquare_com_site_loam_data_variable_assets_default_settings() {
$variable_assets = array();

$variable_assets = array(
  'ds_about_teaser__content_block__image' => array(
    'fid' => 695,
    'uid' => 1,
    'filename' => 'Latvia-currency.jpg',
    'uri' => 'public://designssquare_com_theme_blocks/assets/img/Latvia-currency.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 371034,
    'status' => 1,
    'timestamp' => 1407275746,
    'uuid' => '6c31e986-70f0-49aa-9c4a-6cd4ad5c7aa8',
    'rdf_mapping' => array(),
  ),
);
return $variable_assets;
}
