<?php
/**
 * @file
 * designssquare_com_site_loam_structure.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function designssquare_com_site_loam_structure_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '<em class="icon-resize-horizontal"></em>Max-width 1200px',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '02ef3937-6bc1-4e5f-b654-ee17695f988e',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"></em>jQuery plugins',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '067af360-f093-426f-8ca1-e75cc2d75a6d',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"> </em> MSP Draudze',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '10caebcb-ed8c-4b3f-9dcb-875bd61220b2',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-th"></em>12-column grid',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '11c89891-6ec7-48a6-9680-315d87774539',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"> </em> MKGPF',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1ca10335-3045-4d37-9f14-7953469c16be',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-cog"></em> Latviešu Koncertapvienība MN',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '21b4ce7e-6d45-44fa-b8ff-914c6e3c5500',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<a href="content/kkm"><em class=" icon-cog"></em> KKM</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2395718f-175f-4676-8837-9e3d17a9a4b4',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<a href="content/daugavas-vanagi"><em class="icon-cog"> </em> Daugavas Vanagi</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '23cd8c51-5f47-4dc9-8c6f-d3f3050e1579',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<a href="content/akadēmiskā-kopa"><em class=" icon-cog"> </em> Akadēmiskā kopa</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '27d927a9-6ea8-4df5-bc8f-4f60e586a4a1',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => 'none',
    'description' => 'there is no sidebar',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '3656f50c-c9b3-476d-b225-cf52f279949a',
    'vocabulary_machine_name' => 'post_sidebar',
  );
  $terms[] = array(
    'name' => 'Audios',
    'description' => 'All Audio Posts',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3cef33ef-6ecf-4f0e-bb4b-e66ab7a2b122',
    'vocabulary_machine_name' => 'blog_categories',
  );
  $terms[] = array(
    'name' => 'Small',
    'description' => 'post with small image or video',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '4724e570-b398-44db-bc53-db323445d51c',
    'vocabulary_machine_name' => 'post_format',
  );
  $terms[] = array(
    'name' => '<a href="content/tarts"><em class=" icon-cog"> </em> TARTS</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5038f9aa-87db-426e-86f2-319c64ea1f80',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => 'Text Posts',
    'description' => 'All Text Posts',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '553f1ea7-4573-4bab-8cb1-b8810e30e283',
    'vocabulary_machine_name' => 'blog_categories',
  );
  $terms[] = array(
    'name' => '<em class="icon-list-alt"></em>Styleguide docs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6178e85c-7716-470a-8a84-6701569ff80b',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-resize-small"></em>Responsive design',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '660b13f6-046f-4a13-a889-65aa19fefd01',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => 'left',
    'description' => 'there is sidebar on left',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '6dbf4c34-4e34-4ed7-aaa3-f4991036be13',
    'vocabulary_machine_name' => 'post_sidebar',
  );
  $terms[] = array(
    'name' => '<a href="content/mspd-koris"><em class=" icon-cog"> </em> MSPD Koris</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '75efd7d9-b71e-4ba1-bd65-ea3abcf92a4f',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => 'Big',
    'description' => 'post with large image or video',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '770c84f6-5cf0-4310-b306-66f4c0037afc',
    'vocabulary_machine_name' => 'post_format',
  );
  $terms[] = array(
    'name' => '<a href="content/sp-latviešu-katoļu-draudze"><em class="icon-cog"> </em> SP Latviešu katoļu draudze</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7c69ea01-9c90-4b88-84cd-f11760e3ff66',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<a href="content/lk-sabiedrība"><em class="icon-cog"> </em> LK Sabiedrība</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '85a1fb3f-d3af-49c6-b86c-f17cd22b4430',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => 'Image Posts',
    'description' => 'All Image Posts',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8aeb7d0f-2eaa-477b-9320-87c89191c6a4',
    'vocabulary_machine_name' => 'blog_categories',
  );
  $terms[] = array(
    'name' => '<a href="content/perkonītis"><em class=" icon-cog"> </em> Perkonītis</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9ea8fdba-6165-4846-b47b-fe6a0e61010c',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<a href="content/latviešu-skola"><em class="icon-cog"> </em> Latviešu Skola</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ba4da224-065c-4098-9ce3-664ac11eed7d',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => 'Videos',
    'description' => 'All Video Posts',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'bbe940de-d14e-4f41-8eff-eccba132453a',
    'vocabulary_machine_name' => 'blog_categories',
  );
  $terms[] = array(
    'name' => 'right',
    'description' => 'there is sidebar on right',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bdfd197f-6e7f-489e-94cc-cfd7ea290a70',
    'vocabulary_machine_name' => 'post_sidebar',
  );
  $terms[] = array(
    'name' => 'Uncategorized',
    'description' => 'All Uncategorized Posts',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c91c0033-2fb4-4bbd-b74c-2b6f381b3f7d',
    'vocabulary_machine_name' => 'blog_categories',
  );
  $terms[] = array(
    'name' => '<em class="icon-user"></em>Built for and by nerds',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd81daa80-66c6-4218-91d8-68365e3474a1',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<a href="content/teiksma"><em class=" icon-cog"> </em> Teiksma</a>',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dfd9df67-f88a-46e3-94bb-47cf29e29a78',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-book"></em>Growing library',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e30910ae-5afe-4f81-8f89-9b441451d456',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<em class="icon-eye-open"></em>Cross-everything',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e6440aab-17a5-407b-b97e-f37080cee43c',
    'vocabulary_machine_name' => 'features',
  );
  $terms[] = array(
    'name' => '<a href="content/selga"><em class=" icon-cog"> </em> SELGA</a>',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'fe40396c-8b2b-4c3d-a510-b139cda8970c',
    'vocabulary_machine_name' => 'features',
  );
  return $terms;
}
