<?php
/**
 * @file
 * designssquare_com_site_loam_structure.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function designssquare_com_site_loam_structure_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['views-12b3d239d955afc52dc100c004952fe4'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '12b3d239d955afc52dc100c004952fe4',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'builder' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'builder',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-32335bc5400b4ca82a980e8ac0deae2c'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '32335bc5400b4ca82a980e8ac0deae2c',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'builder' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'builder',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-8bc7f963ccf671e1a1451b0287cae1a7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '8bc7f963ccf671e1a1451b0287cae1a7',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'builder' => array(
        'region' => 'footer_middle',
        'status' => 1,
        'theme' => 'builder',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-a0e8836c61ddefdf3387ea06190d029c'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'a0e8836c61ddefdf3387ea06190d029c',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'builder' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'builder',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-b52596459ce1ba1be9b343628c7da9cf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'b52596459ce1ba1be9b343628c7da9cf',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'builder' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'builder',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-cbc7777e2ba5e694cac3c6fa22db65e7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cbc7777e2ba5e694cac3c6fa22db65e7',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'builder' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'builder',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-d8bb899c125f5a8fab407cf7ab6372e5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'd8bb899c125f5a8fab407cf7ab6372e5',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'builder' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'builder',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
